CONFIG := ./config.h
LIBS   := ./src-cpp/librdkafka++.a  \
          ./src/librdkafka.a
ECONF_FLAGS :=

SDK_ROOT := $(abspath $(shell pwd)/../../otx-sdk-6.2.0)


ifeq ($(PLATFORM), MC-E)
ECONF_FLAGS := --cc=$(CCC) --cxx=$(CCXX) --arch=arm64 
endif

all: $(LIBS)

$(CONFIG):
	@echo "configuring librdkafka"
	./configure --disable-sasl --disable-ssl $(ECONF_FLAGS)

$(LIBS): $(CONFIG)
	@echo "building librdkafka"
	CXX=$(CXX) CC=$(CC) PLATFORM=$(PLATFORM) make libs

clean:
	@echo "cleaning librdkafka"
	make distclean
